"""empty message

Revision ID: e6cd5e49cb8d
Revises: 
Create Date: 2021-08-06 14:09:00.568002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6cd5e49cb8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_one_name', sa.Text(), nullable=True),
    sa.Column('player_one_mark', sa.Text(), nullable=True),
    sa.Column('player_two_name', sa.Text(), nullable=True),
    sa.Column('player_two_mark', sa.Text(), nullable=True),
    sa.Column('board', sa.Text(), nullable=True),
    sa.Column('last_player', sa.Text(), nullable=True),
    sa.Column('winner', sa.Text(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
